# Generated by Django 6.0.3 on 2026-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_member_contact_member_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
